version: '3.8'

services:
  jahia:
    image: 'jahia/jahia-ee-dev:8.2.0.0-SNAPSHOT'
    container_name: jahia
    deploy:
      resources:
        limits:
          memory: 4gb
    environment:
      SUPER_USER_PASSWORD: 'root1234'
      PROCESSING_SERVER: 'true'
      MAX_RAM_PERCENTAGE: 80
      RESTORE_MODULE_STATES: 'false'
      JPDA: 'true'
    ports:
      - '8000:8000'
      - '8080:8080'
      - '8101:8101'
    extra_hosts:
      - jahia:127.0.0.1
    volumes:
      - ./modules:/var/jahia/sources
      - ./patches:/var/jahia/patches/remote
    networks:
      - jahia
networks:
  jahia:
    driver: bridge
    # default MTU size in docker-compose is 1500
    driver_opts:
      com.docker.network.driver.mtu: 1440
